name: Convox Run
description: Run a command
author: Convox
inputs:
  host:
    required: false
    default: console.convox.com
  password:
    required: false
  rack:
    required: false
  app:
    required: true
  release:
    required: true
  service:
    required: true
  command:
    required: true
runs:
  using: docker
  image: Dockerfile
